import type { Metadata } from "next";
import { Bai_Jamjuree } from "next/font/google";
import "./globals.css";

const bai = Bai_Jamjuree({
  weight : ['400','600'] ,
  subsets: ["latin"] });

export const metadata: Metadata = {
  title: "clipboard-landing-page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={bai.className}>{children}</body>
    </html>
  );
}
